version: "3.8"

services:

  mc:
    volumes:
        - ./data:/data
    environment:
        - EULA=TRUE
        - MEMORY=6G
        - RCON_PASSWORD=packwiz
        - TYPE=NEOFORGE
        - VERSION=1.21.1
        - PACKWIZ_URL=https://raw.githubusercontent.com/codecraft3r/mc-dev-pack/refs/heads/main/pack.toml
        - ENABLE_RCON=TRUE
    image: itzg/minecraft-server
    networks:
      lan:
      mc-net:
        aliases:
          - server
    ports:
      - "25565:25565"
    expose:
      - "25575"
    restart: always
    healthcheck:
      test: mc-health
      start_period: 5m
      interval: 30s
      timeout: 10s
      retries: 3

  backup:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "12h"
      RCON_HOST: server
      RCON_PASSWORD: packwiz
      INITIAL_DELAY: 10m
    volumes:
      - ./data:/data:ro
      - ./backup:/backups
    networks:
      - mc-net
    restart: always
    depends_on:
      mc:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.25'

networks:
  mc-net:
  lan:
    driver: bridge
